# Generated by Django 3.2.12 on 2023-12-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_start_date', models.DateTimeField(blank=True, null=True)),
                ('activity_end_date', models.DateTimeField(blank=True, null=True)),
                ('activity_max_students', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activityassignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ActivityAssignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activityregistrations',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ActivityRegistrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authentications',
            fields=[
                ('authentication_id', models.AutoField(primary_key=True, serialize=False)),
                ('authentication_username', models.CharField(max_length=15, unique=True)),
                ('authentication_password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Authentications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=15, null=True)),
                ('course_description', models.CharField(blank=True, max_length=100, null=True)),
                ('course_max_students', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Enrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_course', models.IntegerField(blank=True, null=True)),
                ('grade_laboratory', models.IntegerField(blank=True, null=True)),
                ('grade_seminar', models.IntegerField(blank=True, null=True)),
                ('grade_final', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupactivities',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('activity_duration', models.IntegerField(blank=True, null=True)),
                ('min_participants', models.IntegerField(blank=True, null=True)),
                ('expiration_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GroupActivities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupmembers',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GroupMembers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupmessages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_context', models.CharField(blank=True, max_length=255, null=True)),
                ('message_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GroupMessages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('laboratory_id', models.AutoField(primary_key=True, serialize=False)),
                ('laboratory_name', models.CharField(blank=True, max_length=15, null=True)),
                ('laboratory_description', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratory_max_students', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Laboratories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seminars',
            fields=[
                ('seminar_id', models.AutoField(primary_key=True, serialize=False)),
                ('seminar_name', models.CharField(blank=True, max_length=15, null=True)),
                ('seminar_description', models.CharField(blank=True, max_length=100, null=True)),
                ('seminar_max_students', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Seminars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studygroups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=30, null=True)),
                ('group_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'StudyGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_pic', models.CharField(db_column='user_PIC', max_length=20, unique=True)),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=50)),
                ('user_phone_number', models.CharField(max_length=20, unique=True)),
                ('user_email', models.CharField(max_length=50)),
                ('user_iban', models.CharField(db_column='user_IBAN', max_length=30, unique=True)),
                ('user_contract_number', models.IntegerField(unique=True)),
                ('user_type', models.CharField(max_length=15)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sharedmodels.users')),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sharedmodels.users')),
                ('student_study_year', models.IntegerField()),
                ('student_hours', models.IntegerField()),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Superadmins',
            fields=[
                ('super_admin', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sharedmodels.users')),
            ],
            options={
                'db_table': 'SuperAdmins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sharedmodels.users')),
                ('teacher_department', models.CharField(max_length=30)),
                ('teacher_min_hours', models.IntegerField()),
                ('teacher_max_hours', models.IntegerField()),
            ],
            options={
                'db_table': 'Teachers',
                'managed': False,
            },
        ),
    ]
