# Generated by Django 4.2.7 on 2024-01-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmodels', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
        ('sharedmodels', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
    ]
