# Generated by Django 4.2.7 on 2024-01-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmodels', '0003_merge_20240113_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentenrollments',
            fields=[
                ('student_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StudentEnrollments',
                'managed': False,
            },
        ),
    ]
